---
# -----------------------------------------------
# Ansible Playbook
# Author: Natan Anael <natan.anael@gmail.com>
# Description: This playbook will setup an
# environment with Debian_8_Testing SO.
# vim: ft=ansible
# -----------------------------------------------

- hosts: 127.0.0.1
  connection: local
  remote_user: root
  become: yes
  become_method: su
  tasks:

  - apt_repository: repo='deb http://ftp.us.debian.org/debian/ stretch main contrib non-free' state=present
  - apt_repository: repo='deb http://ftp.us.debian.org/debian/ jessie main contrib non-free' state=present
  - apt_repository: repo='deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free' state=present
  - apt_repository: repo='deb http://ftp.us.debian.org/debian/ jessie-updates contrib main non-free' state=present
  - apt_repository: repo='deb http://ftp.us.debian.org/debian/ jessie-proposed-updates contrib main non-free' state=present
  - apt_repository: repo='deb http://security.debian.org/ jessie/updates contrib main non-free' state=present
  - apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present
  - apt_key: id="EEA14886" keyserver="hkp://keyserver.ubuntu.com:80" state=present

  - name: Upgrade all packages
    apt: upgrade=dist update_cache=yes dpkg_options='force-confold,force-confdef'

  - name: Install (a lot of) useful packages using APT
    apt: pkg={{ item }} state=present install_recommends=yes
    with_items:
      - wget
      - awscli
      - python-boto
      - python3-boto
      - python-dev
      - python3-dev

  - name: Install docker-ce
    apt: update_cache=yes name=docker-ce state=latest-

  - name: Get the latest Google Chrome installer
    get_url: url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" dest=/usr/local/src/chrome.deb

  - name: Install Google Chrome Browser
    apt: deb="/usr/local/src/chrome.deb"

  - name: Get the latest Slack installer
    get_url: url="https://downloads.slack-edge.com/linux_releases/slack-desktop-2.0.3-amd64.deb" dest=/usr/local/src/slack.deb

  - name: Install Slack
    apt: deb="/usr/local/src/slack.deb"

  - name: Append user to docker group
    user: name={{ main_user }} groups=docker append=yes
