- hosts: 127.0.0.1
  connection: local
  remote_user: root
  become: yes
  become_method: sudo
  tasks:

  - name: Remove old custom packages
    shell:
      cmd: rm -rf /etc/apt/sources.list.d/*
  
  - name: Install basic packages
    apt:
      state: present
      update_cache: yes
      pkg:
      - awscli
      - curl
      - python-dev
      - python3-dev
      - python-pip
      - python3-pip
      - r-base
      - wget
  
  - name: Install pip basic packages
    pip:
      name:
      - beautifulsoup4
      - boto3
      - flask
      - jupyterlab
      - keras
      - matplotlib
      - numpy
      - pandas
      - requests
      - scipy
      - scikit-learn
      - seaborn
      - tensorflow
  
  - name: Install R studio
    apt:
      deb: https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.5033-amd64.deb
  
  - name: Install VSCode
    shell:
      cmd: snap install code
  
  - name: Install DBeaver
    apt:
      deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb

  - name: Install docker packages requirements
    apt:
      state: present
      update_cache: yes
      pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
  
  - name: Add Docker GPG key
    shell:
      cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install Docker
    apt:
      state: present
      update_cache: yes
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  
  - name: Create docker group
    group:
      name: docker
      state: present
  
  - name: Add user to docker group
    user:
      name: natan
      append: yes
      group: docker
